### PR TITLE
Add CleanShot

### PR DESCRIPTION
**Pull request by fmerian**
https://cleanshot.com/

### CODE REVIEW

**Review by jyguyomarch — CHANGES_REQUESTED** [review]
Looks like a great polished solution. I would also mention in the description that the solution has no free options. At least I could not find any.

**Comment by fmerian** [comment]
> I would also mention in the description that the solution has no free options.

thanks, @jyguyomarch! 

how would you mention it? couldn't find any examples in the file. 

also, for accuracy: 
> [CleanShot] doesn't provide a trial, but [it] has a 30-day money-back guarantee (...) CleanShot is also available with [Setapp](https://go.setapp.com/stp226?refAppID=321), which does have a 7-day free trial.

source: [CleanShot](https://cleanshot.com/pricing)

**Comment by fmerian** [comment]
how about this @jyguyomarch?

**Comment by jyguyomarch** [comment]
Thx for the rework @fmerian

**Pull request merged**
