### PR TITLE
Add Bitwarden Password Manager to Password Managers

### PR DESCRIPTION
**Pull request by raheelrjunaid**
[Bitwarden](https://bitwarden.com/) is an open-source password manager. I believe it should be included as it on par with the quality of LastPass while retaining a "free forever" subscription option.

### CODE REVIEW

**Comment by nitrocode** [comment]
Yes. LastPass is nice and bitwarden is a worthy competitor since bitwarden can be used on desktop and mobile for free and it's open source.

**Comment by nitrocode** [comment]
cc: @jyguyomarch

**Comment by jyguyomarch** [comment]
Thx @nitrocode for the ping. Need to spend some time on the recent proposals. Will review and clean up soon.

**Review by jyguyomarch — CHANGES_REQUESTED** [review]
Can you simply move it up as all Awesome List should be ordered alphabetically? Also use an Em Dash instead of the short one

**Comment by raheelrjunaid** [comment]
@jyguyomarch Applied the fixes requested.

**Review by jyguyomarch — APPROVED** [review]

**Comment by jyguyomarch** [comment]
Thx @raheelrjunaid I made you change it for an em dash but just discovered that guideline is back to using en dash. Sorry for that. Will revert this myself 😄

**Comment by raheelrjunaid** [comment]
@jyguyomarch I noticed that too! Thanks 😄

**Pull request merged**
